# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb-lista-rango
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: lista-rango
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
